version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: data_engineer_practice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./python:/opt/airflow/dags/python
      - ./data:/opt/airflow/dags/data
